### ISSUE TITLE
Specify Ruby Version

### ISSUE THREAD

**Issue by jeduardo824** [victor-am/ruby_detective#9]
Hi!

On the README, we don't find any information about the Ruby version that should be used.
I tried to run with version `2.4.6`, but the method `prepend` is not available for Arrays on the mentioned version. 

When I used the version `2.6.2`, everything was fine.

As far as I know, `prepend` is available for Arrays only on versions >= `2.5` (On `2.4` prepend was available only for `Strings` and `Modules`)

**Comment by victor-am** [comment]
Nice catch, thanks for reporting 😄 
Gonna be fixed asap 👍

**Comment by victor-am** [comment]
Fixed on 57a66e4ac393fc914b7e50d7dfa2bbd749df018a 🎉 
Thanks again for the issue report!
